# What is NumPy?
**NumPy** stands for ***Numerical Python***.

It is a Python library used for:

- Fast numerical calculations
- Working with arrays
- Mathematical operations
- Scientific computing
- Data analysis

NumPy provides a powerful object called:
**ndarray (N-dimensional array)**
y)

This array allows you to store and process large amounts of numerical data much faster than normal Python lists.

In [1]:
#creating simple array
import numpy as np
array = np.array([1,2,3,4,5])
print("This is simple array:",array)

This is simple array: [1 2 3 4 5]


# NumPy vs Python Lists


Both store data, but NumPy arrays are faster and more powerful.

In [2]:
import numpy as np
# python list
python_list = [1,2,3,4]

#numpy array
numpy_array = np.array([1,2,3,4])

print("PythonList :" , python_list)
print("NumpyArray :", numpy_array)
      

PythonList : [1, 2, 3, 4]
NumpyArray : [1 2 3 4]


# Creating NumPy Arrays
**np.array() Function**

***np.array()*** is the main function used to create a NumPy array.

It converts **Python lists or tuples** into NumPy arrays.

NumPy arrays are used to store **numerical data** in a structured and fast way, which is essential for data science and machine learning.

In [3]:
import numpy as np
# createing a numpy array from a python list
arr= np.array([12,34,56,67]) #pyhton list converts it into a numpy array 
print(arr)

[12 34 56 67]


# 1D Arrays :
A **1D array** is like a **single row of numbers***.

It is similar to a Python list but faster and more powerful.

In [4]:
import numpy as np

arr1 = np.array([13,45,65,35])
print(arr1)
print("The Shape of array is :",arr1.shape)

[13 45 65 35]
The Shape of array is : (4,)


# 2D Arrays :
A **2D array** contains **rows and columns.**

It looks like a **table or spreadsheet.**

This is very common in datasets used in data science.

In [5]:
import numpy as np
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8]    #Two rows
                 #four columns
]) 
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [6]:
import numpy as np 
arr2 = np.array([
    [1,2],
    [3,4],
    [5,6]])
print(arr2)
print("shape of array",arr2.shape)

[[1 2]
 [3 4]
 [5 6]]
shape of array (3, 2)


# 3D Arrays :
A **3D array** contains **multiple 2D arrays stacked together**.

It is used in:

- Image processing
- Deep learning
- Video data

In [7]:
import numpy as np
arr3 = np.array([   # 2 blocks
    [[1,2],[3,4]],  # 2 rows
    [[5,6],[7,8]]   # 2 columns
])
print (arr3)
print (arr3.shape)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [8]:
import numpy as np
arr3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
])
print(arr3)
print("shape is :",arr3.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
shape is : (3, 2, 2)


# dtype Concept :
**dtype** means **Data Type** of elements inside the NumPy array

Common types:

| dtype | Meaning |
|-------|---------|
| int32	| Integer numbers
| float64| 	Decimal numbers
| bool	 | True/False
| str	 | Text

NumPy uses fixed data types, which makes it very fast.

In [9]:
import numpy as np
arr = np.array([12,34,56])
print("Data Type is :",arr.dtype) 

Data Type is : int32


In [10]:
#Creating array with specific dtype

import numpy as np
arr=np.array([1,2,4], dtype=float)
print(arr)
print("dtype is :",arr.dtype)

[1. 2. 4.]
dtype is : float64


In [11]:
import numpy as np 
arr= np.array([1,2,3,4,5,6,7],dtype=float)
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5. 6. 7.]
float64


In [12]:
import numpy as np
array = np.array([
    [25,30,35],
    [40,45,50],
    [55,60,65]
])

print(array)
print("Shape is : ",array.shape)
print("dtype is :",array.dtype)
print("no of elements : ",array.size)

[[25 30 35]
 [40 45 50]
 [55 60 65]]
Shape is :  (3, 3)
dtype is : int32
no of elements :  9


# 3️⃣ Special Array Creation in NumPy
These functions are extremely important in **Data Science and Machine Learning**, because we often need to generate arrays quickly for **experiments, simulations, and models.**

Libraries like ***Scikit-learn, TensorFlow, and PyTorch*** internally use these types of arrays.

# 1 — np.zeros() :
**np.zeros()** creates an array filled with **0 values**.

It is useful when you want to initialize a **dataset or matrix with zeros.**

In [13]:
import numpy as np
arr = np.zeros((3,4)) # 3 rows and 4 column with zeros
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
import numpy as np 
arr0 = np.zeros((2,5))
print(arr0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 2 — np.ones():
**np.ones()** creates an array filled with **1 values.**

In [15]:
import numpy as np
arr1 = np.ones((2,4))
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 3 — np.arange() :
***np.arange()*** generates numbers in a **sequence.**

Similar to Python range() but returns a NumPy array.

In [16]:
import numpy as np
npr = np.arange(0,10) # print 0 to 10 numbers
print(npr)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
# With Step Size
arr = np.arange(0,10,2) #start, stop, step
print(arr)

[0 2 4 6 8]


In [18]:
arr2 = np.arange(5,50, 5)
print (arr2)

[ 5 10 15 20 25 30 35 40 45]


# 4 — np.linspace() :
**np.linspace()** creates **evenly spaced numbers between two values**.

Instead of step size, you specify how many numbers you want.

Example : Imagine dividing a road of 100 meters into 5 equal checkpoints.

0m --- 25m --- 50m --- 75m --- 100m

That equal division is like linspace.

**Think of it like a ruler: you tell NumPy where to start, where to end, and how many "marks" (numbers) you want in between. NumPy then calculates the exact distance between each mark so they are perfectly even.**

In [19]:
import numpy as np 
arr = np.linspace(0,10,5) # start, stop, number_of_values

print(arr)  #Start → 0
            #End → 10
            #Create → 5 evenly spaced numbers.

[ 0.   2.5  5.   7.5 10. ]


In [20]:
arr1 = np.linspace(0,100,8)
print(arr1)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


#  5 — np.eye() :
**np.eye()** creates an **identity matrix.**

Identity matrix rules:

- Diagonal = 1
- Others = 0


 1

In [21]:
import numpy as np 
arr = np.eye(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 6 — np.random :
***np.random*** generates **random numbers.**

Used in:

-  Learning
- Simulations
- Data generation
- Model testing

In [22]:
# Random Numbers (0-1)

import numpy as np 
arr = np.random.rand(3,3) #Creates 3×3 random numbers between 0 and 1.
print(arr)

[[0.0462099  0.99057553 0.58409704]
 [0.78652689 0.29015566 0.92328071]
 [0.35502817 0.12343707 0.29506259]]


In [23]:
# Random Integers

import numpy as np 
arr1 = np.random.randint(1,10,(3,3)) #Random integers from 1 to 9.
print(arr1)

[[9 9 9]
 [4 6 4]
 [5 3 1]]


In [24]:
# Random Normal Distribution

import numpy as np

arr2 = np.random.randn(3,3)
print(arr2)

[[ 0.99093293  0.16686788 -0.52397121]
 [-0.67606107 -0.99595838 -1.98609594]
 [-0.16291741 -0.17835945  0.4104867 ]]


In [25]:
import numpy as np
arr3 = np.random.randint(10,50,(2,4))
print(arr3)

[[43 32 14 17]
 [47 33 39 37]]


In [26]:
# pratice
import numpy as np 
arr = np.zeros((3,3))
arr1 = np.ones((2,5))
arr2 = np.arange(10,10,100)
arr3 = np.eye(4)
arr4 = np.random.randint(1,20,(3,3))
arr5 = np.linspace(0,1,5)

print("1️⃣ Zero Matrix :" ,arr)
print("2️⃣ ones Matrix :",arr1)
print("3️⃣ Numbers from 10 to 100 step 10 :",arr2)
print("4️⃣ linspace 5 evenly spaced numbers between 0 and 1 :",arr5)
print("5️⃣ 4×4 identity matrix :",arr4)
print("6️⃣ Random 3×3 integer matrix between 1-20 :",arr4)
      

1️⃣ Zero Matrix : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2️⃣ ones Matrix : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
3️⃣ Numbers from 10 to 100 step 10 : []
4️⃣ linspace 5 evenly spaced numbers between 0 and 1 : [0.   0.25 0.5  0.75 1.  ]
5️⃣ 4×4 identity matrix : [[ 9  6 14]
 [11  6 14]
 [ 7 16 15]]
6️⃣ Random 3×3 integer matrix between 1-20 : [[ 9  6 14]
 [11  6 14]
 [ 7 16 15]]


# 4️⃣ Array Attributes :
In NumPy, **array attributes help us understand the structure and properties of an array.**

The most important attributes every Data Scientist uses are:

- .shape
- .ndim
- .size
- .dtype

These attributes help us **analyze datasets before building machine learning models**

Libraries like **Pandas, Scikit-learn, and TensorFlow** rely heavily on NumPy arrays.

# 1 — .shape :
***.shape*** tells us the **structure of the array.**

It returns:

(rows, columns)

or more dimensions if the array is 3D or higher.

In [27]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.shape)

(2, 3)


# 2 — .ndim :
**.ndim** tells us how many **dimensions the array has.**

Examples:

|Array | Type	| Dimensions|
|------|--------|-----------|
|1D    |array	|        1  |
|2D    |array	|        2  |
|3D    |array	|        3   |

In [28]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.ndim)

2


In [29]:
arr1 = np.array([12,34,56])
print("Ndim :",arr1.ndim)

Ndim : 1


# 3 — .size:
**.size** tells us the **total number of elements in the array.**

In [30]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print("size :",arr.size)

size : 6


# 4 — .dtype :
.dtype shows the data type of elements inside the array.

In [31]:
import numpy as np

arr = np.array([10,20,30,40])

print(arr.dtype)

int32


In [32]:
#pratice 
import numpy as np
arr = np.array([
    [12,24,36],
    [48,60,72],
    [84,96,108]
])
print("shape : ",arr.shape)
print("dimension : ",arr.ndim)
print("size :",arr.size)
print("datatype :",arr.dtype)

shape :  (3, 3)
dimension :  2
size : 9
datatype : int32


# 5️⃣ Array Indexing

**Array indexing** allows us to **access specific elements from a NumPy array.**

This is one of the most frequently used skills in data science, because datasets often contain thousands or millions of values, and we need to extract specific parts of them.

Libraries such as Pandas, Scikit-learn, and TensorFlow heavily rely on this concept.

# Accessing Elements (1D Array)

In NumPy arrays, every element has an **index position.**

Indexing always starts from 0.

Example:

Index : 0   1   2   3

Value : 10  20  30  40

In [33]:
import numpy as np 
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[3])
      

1
4


# Accessing Elements in 2D Arrays :

In 2D arrays, indexing uses **two positions:**

- array[row][column]

or

- array[row, column]

In [34]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr[0,1])
print(arr[1,2])

20
60


In [35]:
arr1 = np.array([
    [5,10,15],
    [20,25,30]
])
print(arr1[0,1])
print(arr1[1,2])
      

10
30


# 3 — Accessing Entire Rows :
**To access a full row**, we use:

***array[row]***

In [36]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr[0])
print(arr[1])

[10 20 30]
[40 50 60]


In [37]:
arr1 =np.array([
    [2,4,6],
    [8,10,12],
 [  14,16,18]
])
print(arr1[1])


[ 8 10 12]


# 4 — Accessing Entire Columns
To access a column, we use:

**array[:, column]**

The **:** symbol means select all rows.

In [38]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr[:,0])
print(arr[:,2])

[10 40 70]
[30 60 90]


In [39]:
# pratices 

arr1 = np.array([
    [25,30,35],
    [40,45,50],
    [55,60,65]
])
print("first row : ", arr1[0])
print("second column :",arr1[:,1])
print("last element : ",arr1[2,2])

first row :  [25 30 35]
second column : [30 45 60]
last element :  65


# 6️⃣ Array Slicing :
**Array slicing** allows us to **extract a portion of an array instead of a single element.**

This is extremely useful when working with **datasets**, because we often need to **select ranges of data rather than individual values.**

Data scientists frequently use slicing in libraries like **Pandas, Scikit-learn, and TensorFlow.**

# 1 — What is Slicing?
Slicing means **selecting a range of elements from an array.**

General syntax:

**array[start : end]**

Important rule:

- start → included
- end → excluded

# 2 — 1D Array Slicing :
In 1D arrays, **slicing extracts a range of elements from a single row.**

In [40]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

print(arr[1:4])

[20 30 40]


# 3 — 2D Array Slicing:
For 2D arrays, slicing includes **rows and columns.**

Syntax:

```array[row_start:row_end , column_start:column_end]```

In [41]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr[0:2 , 1:3])

[[20 30]
 [50 60]]


# 4 — Step Slicing :
Step slicing **selects elements with a specific interval.**

Syntax:

```array[start:end:step]```

In [42]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

print(arr[0:6:2])

[10 30 50]


In [43]:
# pratice 

import numpy as np 
arr1 = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
])

print("slice first two rows:",arr1[0:2])
print("2️⃣ slice last two columns : ",arr1[:,2:4])
print("3️⃣ slice every second column : ",arr1[:,::2]) #Select all rows
                                                     #Select columns with step = 2

                                                     #So it skips every second column and returns every alternate column.

slice first two rows: [[10 20 30 40]
 [50 60 70 80]]
2️⃣ slice last two columns :  [[ 30  40]
 [ 70  80]
 [110 120]]
3️⃣ slice every second column :  [[ 10  30]
 [ 50  70]
 [ 90 110]]


# PHASE 2 — Array Operations (Core NumPy)

# 7️⃣ Mathematical Operations

**NumPy** allows us to perform **mathematical operations on entire arrays at once.**

This is called **vectorized computation**, which makes calculations much faster than normal Python loops.

These operations are heavily used in libraries **like Scikit-learn, TensorFlow, and PyTorch.**

# 1 — Addition :
NumPy allows **element-wise addition between arrays.**

Each element in one array is added to the corresponding element in the other array.

In [44]:
import numpy as np

arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])

result = arr1 + arr2

print(result)

[11 22 33]


In [45]:
import numpy as np
arr = np.array([5,10,15])
arr1 = np.array([2,4,6])
result = arr + arr1
print(result)

[ 7 14 21]


# 2 — Subtraction
Subtraction also works **element by element.**

In [46]:
import numpy as np

arr1 = np.array([50,60,70])
arr2 = np.array([10,20,30])

result = arr1 - arr2

print(result)

[40 40 40]


# 3 — Multiplication :
Multiplication multiplies elements **position by position.**

In [47]:
import numpy as np

arr1 = np.array([2,4,6])
arr2 = np.array([10,20,30])

result = arr1 * arr2

print(result)

[ 20  80 180]


# 4 — Division :
Division divides elements position by position.


In [48]:
import numpy as np

arr1 = np.array([100,200,300])
arr2 = np.array([10,20,30])

result = arr1 / arr2

print(result)

[10. 10. 10.]


In [49]:
# pratice

import numpy as np
a = np.array([10,20,30])
b = np.array([2,4,6])

print("Addition: ",a+b)
print("Subtraction :",a-b)
print("multiplication:",a*b)
print("division:",a/b)

Addition:  [12 24 36]
Subtraction : [ 8 16 24]
multiplication: [ 20  80 180]
division: [5. 5. 5.]


# 8️⃣ Broadcasting :
**Broadcasting** allows NumPy to perform **operations on arrays of different shapes automatically.**

Normally, arrays must have the same shape to perform operations.
But with broadcasting, NumPy intelligently **expands the smaller array to match the larger one.**

This feature is heavily used in **Scikit-learn, TensorFlow, and PyTorch.**

**Broadcasting** is used heavily in **machine learning computations** such as:

- Feature scaling
- Gradient calculations
- Neural network weight updates

# 1 — What is Broadcasting? 
Broadcasting allows operations like:

```
array + number
array + smaller_array
```


NumPy automatically expands the **smaller value to match the shape.**

Example:

[10 20 30] + 5

Result:

[15 25 35]

The number 5 is broadcast to all elements.

# 2 — Broadcasting with Scalars


In [50]:
import numpy as np
arr = np.array([10,20,30])
result = arr+ 5
print(result)

[15 25 35]


# 3 — Broadcasting Between Arrays

Broadcasting also works between arrays of different shapes.

Example:

[1 2 3]
+
[10]

Result:

[11 12 13]
The smaller array is expanded automatically.

# 4 — Broadcasting with 2D Arrays


In [51]:
import numpy as np 
arr =np.array ([
    [1,2,3],
    [4,5,6]
])
result = arr + 10
print(result)

[[11 12 13]
 [14 15 16]]


# 5 — Broadcasting with Different Shapes

In [52]:
import numpy as np
arr1 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
arr2 = np.array([10,20,30,40])
result = arr1 + arr2
print(result)

[[11 22 33 44]
 [15 26 37 48]]


# 🟦 Broadcasting Rules

Broadcasting works when these rules are satisfied.

**Rule 1**

Dimensions must be **equal OR one of them must be 1.**

**Rule 2**

Comparison happens from **right to left dimensions.**

Example:

(2,3)
(3,)

**Rightmost dimensions match → broadcasting works.**

Example of Invalid Broadcasting

- (2,3) -> 2 rows 3 columns

- (2,2) ->2 rows 2 columns

This causes an **error because dimensions don't match.**

In [53]:
# pratice

import numpy as np

A = np.array([
    [10,20,30],
    [40,50,60]
])

B = np.array([1,2,3])

print("Addition :" ,A+B)
print("Multiplication :",A*B)

Addition : [[11 22 33]
 [41 52 63]]
Multiplication : [[ 10  40  90]
 [ 40 100 180]]


# 9️⃣ Aggregation Functions :
Aggregation functions **summarize data into a single value.**

Instead of looking at every number, we calculate statistics like:

- Total
- Average
- Minimum
- Maximum
- Standard deviation

These functions are used heavily in **pandas, NumPy, and machine learning workflows.**

# 1️⃣ np.sum() — Total of Elements


sum() **adds all elements of an array.**

In [54]:
import numpy as np
arr = np.array([1,2,3,4]) #1+2+3+4=10
results =np.sum(arr)
print(results)

10


# 2️⃣ np.mean() — Average Value

mean() calculates the **average of all values.**

Formula:

$$
\bar{x} = \frac{x_1 + x_2 + x_3 + \dots + x_n}{n}
$$
	​

	​


In [55]:
arr = np.array([10,20,30,40])

print(np.mean(arr))

25.0


# 3️⃣ np.min() — Minimum Value


min() finds the **smallest number in the array.**

In [56]:
arr = np.array([15,8,22,5,17])

print(np.min(arr))

5


# 4️⃣ np.max() — Maximum Value


max() finds the **largest number.**

In [57]:
arr = np.array([15,8,22,5,17])

print(np.max(arr))

22


# np.std() — Standard Deviation


Standard deviation measures **how spread out the data is.**

- Small std → data is close to average
- Large std → data is spread out






Meaning:

|Symbol|	Meaning       |
|------|------------------|
|xi    |each value        |
|μ	   |mean              |
|n     |number of values  |
|σ	   |standard deviation|


$$
\sigma = \sqrt{\frac{1}{n}\sum_{i=1}^{n}(x_i-\mu)^2}
$$$$

In [58]:
arr = np.array([10,20,30,40])

print(np.std(arr))

11.180339887498949


# Aggregation with Axis (Very Important)

Aggregation can also work on **rows or columns**

**Example array:**
```
arr = np.array([
    [10,20,30],
    [40,50,60]
])
```
**Column-wise sum:**

np.sum(arr, axis=0)

**Output:**

[50 70 90]

**Explanation:**
```
10 + 40
20 + 50
30 + 60
```
**Row-wise sum**

np.sum(arr, axis=1)

**Output:**

[60 150]

**Explanation :**
```
10+20+30
40+50+60
```


In [59]:
# pratice

import numpy as np
data =np.array([12,15,20,25,30])

print("sum:",np.sum(data))
print("mean:",np.mean(data))
print("min:",np.min(data))
print("max:",np.max(data))
print("std:",np.std(data))

sum: 102
mean: 20.4
min: 12
max: 30
std: 6.529931086925803


# 🔟 Axis Operations (axis = 0 , axis = 1) 
In NumPy, axis tells Python the direction of operation.

When we perform operations like:

- sum()
- mean()
- min()
- max()

NumPy needs to know **whether to operate across rows or columns.**

So we use axis.

**Rule:**
|Axis	 | Meaning                                  |
|--------|------------------------------------------|
|axis = 0|	Operation down the rows (column-wise)   |
|axis = 1|	Operation across the columns (row-wise) |

In [60]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Array:")
print(arr)

# axis = 0
print("\nSum axis=0 (column wise):")
print(np.sum(arr, axis=0))

# axis = 1
print("\nSum axis=1 (row wise):")
print(np.sum(arr, axis=1))

Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Sum axis=0 (column wise):
[120 150 180]

Sum axis=1 (row wise):
[ 60 150 240]


In [61]:
# pratice :

import numpy as np
arr = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
print("\nArray:",arr)

print("\n 1️⃣ sum using axis=0:",np.sum(arr, axis = 0))
print("\n 2️⃣ sum using axis=1:",np.sum(arr , axis = 1))
print("\n 3️⃣ Find mean using axis=0 :",np.mean(arr , axis = 0))
print("\n 4️⃣ Find max using axis=1:",np.max(arr , axis = 1))


Array: [[ 5 10 15]
 [20 25 30]
 [35 40 45]]

 1️⃣ sum using axis=0: [60 75 90]

 2️⃣ sum using axis=1: [ 30  75 120]

 3️⃣ Find mean using axis=0 : [20. 25. 30.]

 4️⃣ Find max using axis=1: [15 30 45]


# PHASE 3 — Array Manipulation

### 11️⃣ Reshaping Arrays

Reshaping means **changing the shape of an array without changing its data.**

**Example:**

[1 2 3 4 5 6]

can become

[[1 2 3]

 [4 5 6]]

The **data stays the same**, but the **structure changes.**

# 1️⃣ reshape() — Change Array Shape

reshape() changes the **dimensions of an array.**

Important rule:

**Total elements must remain the same**

In [62]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(3,2)

print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


# Using -1 (Automatic Dimension)

NumPy can calculate one dimension automatically.
- NumPy automatically calculates the missing size.

In [63]:
arr = np.array([1,2,3,4,5,6])

arr.reshape(3,-1)


array([[1, 2],
       [3, 4],
       [5, 6]])

# 2️⃣ flatten() — Convert to 1D Array

***flatten()*** converts a **multi-dimensional array into a 1D array.**

It also creates a **copy of the array.**

**Important Point:**

flatten() does **NOT modify the original array.**

In [64]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

flat = arr.flatten()

print(flat)

[1 2 3 4 5 6]


# 3️⃣ ravel() — Flatten Without Copy


ravel() also **converts array to 1D, but it returns a view instead of a copy.**

This means **it uses the same memory.**

In [65]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

flat = arr.ravel()

print(flat)

[1 2 3 4 5 6]


# Key Difference :
|Function	| Copy	| Memory Usage|
|-----------|-------|-------------|
|flatten()	|Yes	|More         |
|ravel()	|No	    |Less         |

In large datasets, **ravel() is faster and more memory efficient.**

# 🟦 Practical Data Science Example

Datasets often come as **2D tables**, but **machine learning models may need 1D arrays.**

**Example:**
```
import numpy as np

image = np.array([
    [255,128],
    [64,0]
])

vector = image.flatten()

print(vector)
```

### Output :

[255 128 64 0]

This is commonly done before **training models in Machine Learning.**

In [66]:
#pratice :
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print("\n Reshape :",arr.reshape(4,2))
print("\n Flatten :",arr.flatten()) # -> returns copy
print("\n Ravel : ",arr.ravel())  # -> return view


 Reshape : [[1 2]
 [3 4]
 [5 6]
 [7 8]]

 Flatten : [1 2 3 4 5 6 7 8]

 Ravel :  [1 2 3 4 5 6 7 8]


# 12️⃣ Joining Arrays :

Joining arrays means **combining two or more arrays into one larger array.**

NumPy provides several functions:

- concatenate()
- vstack()
- hstack()

These are used frequently when **merging features or datasets in Machine Learning.**

# 1️⃣ concatenate() — General Joining


np.concatenate() **joins arrays along an existing axis.**

In [67]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.concatenate((arr1, arr2))

print(result)

[1 2 3 4 5 6]


# concatenate() with 2D Arrays


In [68]:
arr1 = np.array([
    [1,2],
    [3,4]
])

arr2 = np.array([
    [5,6],
    [7,8]
])

result = np.concatenate((arr1, arr2), axis=0)

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# 3️⃣ vstack() — Vertical Stack:

vstack() stacks **arrays row-wise (top to bottom).**

**It is equivalent to:**

**concatenate(axis=0)**

In [69]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.vstack((arr1, arr2))

print(result)

[[1 2 3]
 [4 5 6]]


# 4️⃣ hstack() — Horizontal Stack


hstack() stacks **arrays column-wise (side by side).**

**Equivalent to:**

concatenate(axis=1)

In [70]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.hstack((arr1, arr2))

print(result)

[1 2 3 4 5 6]


In [71]:
# 2D Example
arr1 = np.array([
    [1,2],
    [3,4]
])

arr2 = np.array([
    [5,6],
    [7,8]
])

np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [72]:
# pratice
import numpy as np

A = np.array([10,20,30])
B = np.array([40,50,60])

print("Concatenate:",np.concatenate((A,B)))
print("Vstack:",np.vstack((A,B)))
print("Hstack:",np.hstack((A,B)))


Concatenate: [10 20 30 40 50 60]
Vstack: [[10 20 30]
 [40 50 60]]
Hstack: [10 20 30 40 50 60]


### 🧠 Why Double Parentheses?

Because we pass multiple arrays as one argument (tuple).

Example:

np.concatenate((A,B))

This means:

(A,B)

is a tuple containing two arrays.

# 13️⃣ Splitting Arrays:
Splitting arrays means **dividing one array into multiple smaller arrays.**

NumPy provides these main functions:

- split()
- hsplit()
- vsplit()

These are often used when **preparing datasets for Machine Learning.**


# 1️⃣ split() — General Splitting

np.split() divides an **array into equal parts.**

**Important Rule :**

Array size must be **divisible by number of splits**


In [73]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

result = np.split(arr, 3)

print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]


# 2️⃣ split() with Custom Index:

We can also **split at specific positions.**

In [74]:
arr1 = np.array([10,20,30,40,50,60])

result = np.split(arr1, [2,4]) #Split at index 2 and 4

print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]


# 3️⃣ hsplit() — Horizontal Split

hsplit() splits **arrays column-wise (left to right).**

In [75]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

result = np.hsplit(arr2, 2)

print(result)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


# 4️⃣ vsplit() — Vertical Split


vsplit() splits **arrays row-wise (top to bottom).**

In [76]:
arr3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

result = np.vsplit(arr3, 2)

print(result)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


# Adding / Removing Elements in Arrays:

In NumPy, arrays normally have fixed size, but NumPy provides functions that return a new array when we add or remove elements.
### Functions:
- append() → add element at the end
- insert() → add element at a specific position
- delete() → remove element

# 1️⃣ append() – Add Element at the End


append() **adds new values at the end of an array.**

**⚠️ Important:** It does not modify the original array.
**It creates a new array.**

In [77]:
import numpy as np

marks = np.array([80, 75, 90])

new_marks = np.append(marks, 85)

print(new_marks)

[80 75 90 85]


# 2️⃣ insert() – Add Element at Specific Position:

insert() allows **adding an element at a specific index position.**

**Syntax:**
```
np.insert(array, index, value)
```

In [78]:
import numpy as np

sales = np.array([100, 200, 400])

new_sales = np.insert(sales, 2, 300)

print(new_sales)

[100 200 300 400]


# 3️⃣ delete() – Remove Elements:

delete() **removes elements from a specific index.**

**Syntax:**
```
np.delete(array, index)
```

In [79]:
import numpy as np

data = np.array([10, 20, 999, 30])

clean_data = np.delete(data, 2)

print(clean_data)

[10 20 30]


# 14️⃣ Transpose Operations

Transpose means **converting rows into columns and columns into rows.**

**Example:**

**Original Matrix**

1 2 3

4 5 6

**After transpose:**

1 4

2 5

3 6

**Shape changes from:**

(2,3) → (3,2)

# 1️⃣ .T — Transpose Attribute


***.T*** is the **shortest and most common way to transpose a NumPy array.**

In [80]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


# 2️⃣ transpose() Function:

np.transpose() **does the same operation but as a function.**

**Most developers prefer:**
```
arr.T
```

because ** it is simpler.**

In [81]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

result = np.transpose(arr)

print(result)

[[1 4]
 [2 5]
 [3 6]]


In [82]:
# Shape Demonstration
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.shape)
print(arr.T.shape)

(2, 3)
(3, 2)


# PHASE 4 — Advanced NumPy
## 15️⃣ Boolean Indexing (Filtering Data)

**Boolean indexing** allows you to **filter array elements based on conditions.**

Instead of manually looping through data, NumPy lets you select values using **True/False conditions.**

This is widely used in **NumPy and pandas** when cleaning datasets for Machine Learning.

# 1️⃣ What is Boolean Indexing?

Boolean indexing uses **comparison conditions to create a boolean array (True/False).**

In [83]:
import numpy as np

arr = np.array([10,20,30,40])

print(arr > 20)

[False False  True  True]


# 2️⃣ Filtering Data with Boolean Indexing

Now we use the **boolean condition to filter values.**
- Keep elements where condition is True

In [84]:
import numpy as np

arr = np.array([10,20,30,40])

result = arr[arr > 20]

print(result)

[30 40]


# 3️⃣ Example with Dataset Filtering

#### Imagine a dataset of student marks.
```
marks = np.array([45,60,72,30,90])
```
#### Select students who passed (marks ≥ 50).
```
passed = marks[marks >= 50]

print(passed)
```
#### Output:
```
[60 72 90]
```
This is called **data filtering.**

# 4️⃣ Multiple Conditions

We can apply **multiple conditions using logical operators.**

In [85]:
import numpy as np

arr = np.array([10,20,30,40,50])

result = arr[(arr > 20) & (arr < 50)]

print(result)

[30 40]


In [86]:
# 5️⃣ Boolean Indexing in 2D Arrays

import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60]
])

result = arr[arr > 30]

print(result)

#NumPy checks every element in the matrix.

[40 50 60]


# 6️⃣ Changing Values Using Boolean Indexing :

We can also **modify data.**

Example: Replace negative values with 0.

In [87]:
arr = np.array([5,-3,8,-1,10])

arr[arr < 0] = 0

print(arr)

[ 5  0  8  0 10]


In [88]:
# pratice :
import numpy as np
data = np.array([12,25,18,40,7,33])

print("numbers greater than 20:",data[data > 20])
print("numbers less than 15:",data[data< 15])
print("numbers between 20 and 40:",data[(data > 20) & (data < 40)])

numbers greater than 20: [25 40 33]
numbers less than 15: [12  7]
numbers between 20 and 40: [25 33]


# 16️⃣ Fancy Indexing

***Fancy indexing*** allows you to **select multiple elements from an array using index lists (arrays).**

Instead of selecting elements **one by one**, you can specify **multiple indices at once.**

This technique is widely used in **NumPy and pandas when working with datasets in Machine Learning.**

In [89]:
# 1️⃣ Basic Fancy Indexing (1D Array)
import numpy as np

arr = np.array([10,20,30,40,50])

result = arr[[0,2,4]]

print(result)

[10 30 50]


# 2️⃣ Selecting Elements in Different Order

Fancy indexing can also **reorder elements.**

In [90]:
arr = np.array([10,20,30,40,50]) #The array is returned in the order of indices you specify.

print(arr[[3,1,4]])

[40 20 50]


In [91]:
# 3️⃣ Fancy Indexing with 2D Arrays
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr[[0,2]])

[[1 2 3]
 [7 8 9]]


# 4️⃣ Selecting Specific Elements

We can also select specific row-column pairs.

In [92]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

rows = [0,1,2]
cols = [2,1,0]

print(arr[rows, cols])

#(0,2) → 30
#(1,1) → 50
#(2,0) → 70

[30 50 70]


# Fancy Indexing vs Normal Indexing

| Type            | Example        | Result           |
| --------------- | -------------- | ---------------- |
| Normal indexing | `arr[2]`       | single value     |
| Slicing         | `arr[1:4]`     | continuous range |
| Fancy indexing  | `arr[[0,3,4]]` | selected indices |


In [93]:
# pratice 

import numpy as np

arr = np.array([5,10,15,20,25,30])

print("Fancy indexing :",arr[[1,3,5]])

Fancy indexing : [10 20 30]


# NumPy Random Module

# 1️⃣ np.random.rand() — Random Numbers (0 to 1)

Generates random numbers between 0 and 1 from a uniform distribution.

In [94]:
import numpy as np

arr = np.random.rand(5)

print(arr)

[0.06146309 0.3087529  0.6216636  0.79743431 0.55773739]


# 2️⃣ np.random.randn() — Random Numbers (Normal Distribution)
Explanation:

Generates random numbers from a **standard normal distribution.**

Normal distribution:

- Mean = 0
- Standard deviation = 1

Used heavily in machine learning model initialization.

In [95]:
np.random.randn(5)

array([ 0.00961878, -0.67586577,  0.5453737 , -1.03914152,  0.53624691])

# 3️⃣ np.random.randint() — Random Integers
Explanation:

Generates random integer numbers within a specified range.

In [96]:
np.random.randint(1,10)

6

In [97]:
# multiple values
np.random.randint(1,10,5)

array([5, 8, 8, 1, 2])

# 4️⃣ np.random.choice() — Random Selection
Explanation

Randomly selects values from a list or array.

In [98]:
arr = [10,20,30,40]

np.random.choice(arr)

30

In [99]:
# Select Multiple Values
np.random.choice(arr,3)

array([10, 10, 40])

In [100]:
# Without Repeating Values
np.random.choice(arr,3,replace=False)

array([30, 10, 40])

# 17️⃣ Sorting Arrays

two important functions:

- np.sort()
- np.argsort()

# 1️⃣ np.sort() — Sort Values
Explanation:

np.sort() sorts the values of an array in **ascending order.**

In [101]:
import numpy as np

arr = np.array([40,10,30,20])

result = np.sort(arr)

print(result)

#np.sort() does not change the original array.

[10 20 30 40]


# Sorting 2D Arrays

We can sort along rows or columns.

In [102]:
arr = np.array([
    [3,1,2],
    [6,5,4]
])

print(np.sort(arr))

[[1 2 3]
 [4 5 6]]


In [103]:
# Sorting by Axis
np.sort(arr, axis=0)

array([[3, 1, 2],
       [6, 5, 4]])

# 2️⃣ np.argsort() — Get Sorted Indices


argsort() returns the **indices that would sort the array**, not the values.

In [104]:
arr = np.array([40,10,30,20])

print(np.argsort(arr))
"""
index 1 → 10
index 3 → 20
index 2 → 30
index 0 → 40
"""
# These indices show how to reorder the array.

[1 3 2 0]


'\nindex 1 → 10\nindex 3 → 20\nindex 2 → 30\nindex 0 → 40\n'

In [105]:
arr = np.array([50,20,40,10])

sorted_index = np.argsort(arr)

print(sorted_index)
print(arr[sorted_index])

#So argsort() helps rearrange arrays based on sorted indices.

[3 1 2 0]
[10 20 40 50]


# 18️⃣ Unique & Counting


- np.unique()
- np.bincount()

# 1️⃣ np.unique() — Find Unique Values


np.unique() returns **only the unique (non-repeating) values in an array.**

- Remove duplicates
- 
Return unique values

In [106]:
import numpy as np

arr = np.array([1,2,2,3,4,4,5])

result = np.unique(arr)

print(result)

[1 2 3 4 5]


In [108]:
# 🔹 Unique With Counts

values, counts = np.unique(arr, return_counts=True)

print(values)
print(counts)
"""
1 appears 1 time
2 appears 2 times
3 appears 1 time
4 appears 2 times
5 appears 1 time
"""

[1 2 3 4 5]
[1 2 1 2 1]


'\n1 appears 1 time\n2 appears 2 times\n3 appears 1 time\n4 appears 2 times\n5 appears 1 time\n'

# 2️⃣ np.bincount() — Count Frequency of Integers:

np.bincount() counts **how many times each integer appears.**

Works only with non-negative integers.

In [110]:
import numpy as np

arr = np.array([1,2,1,0,2,1,1])

result = np.bincount(arr)

print(result)
"""
0 appears 1 time
1 appears 4 times
2 appears 2 times
"""

[1 4 2]


'\n0 appears 1 time\n1 appears 4 times\n2 appears 2 times\n'

In [113]:
# pratice :
import numpy as np

arr = np.array([3,1,2,3,4,2,1,3,4,4])

print("1️⃣ Unique values:",np.unique(arr))
print("2️⃣ Count of each value:",np.unique(arr , return_counts=True))
print("3️⃣ Frequency using bincount():",np.bincount(arr))

1️⃣ Unique values: [1 2 3 4]
2️⃣ Count of each value: (array([1, 2, 3, 4]), array([2, 2, 3, 3], dtype=int64))
3️⃣ Frequency using bincount(): [0 2 2 3 3]


# 19️⃣ Linear Algebra :
This is a very important topic because most Machine Learning algorithms rely heavily on Linear Algebra operations using NumPy
.
- Dot Product
- Matrix Multiplication
- np.linalg module

# 1️⃣ Dot Product

The dot product **multiplies corresponding elements of two vectors and then adds them.**
	​


In [115]:
import numpy as np

A = np.array([1,2,3])  # 1×4 + 2×5 + 3×6
B = np.array([4,5,6])  # 4 + 10 + 18 = 32

result = np.dot(A,B)

print(result)

32


# 2️⃣ Matrix Multiplication


Matrix multiplication **multiplies rows of the first matrix with columns of the second matrix.**

**Rule:**

##### columns of A = rows of B

In [117]:
import numpy as np

A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

result = np.matmul(A,B)

print(result)

# [[1×5 + 2×7 , 1×6 + 2×8],
#  [3×5 + 4×7 , 3×6 + 4×8]]

[[19 22]
 [43 50]]


# 3️⃣ np.linalg Module:

***np.linalg*** provides **advanced linear algebra functions.**

###### Common operations:

- Inverse
- Determinant
- Eigenvalues
- Solving equations

In [118]:
# Example 1 — Matrix Inverse

import numpy as np

A = np.array([[1,2],
              [3,4]])

inv = np.linalg.inv(A)

print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


# Example 2 — Determinant

The determinant measures matrix scaling.

det(a  b )

    (c  d)    =ad-bc
  
	​



In [119]:
np.linalg.det(A)

-2.0000000000000004

# Example 3 — Solve Linear Equations

Equation system:
```
2x + y = 5
x + y = 3
```

In [121]:
A = np.array([[2,1],
              [1,1]])

B = np.array([5,3])

x = np.linalg.solve(A,B)

print(x)
# x = 2
# y = 1

[2. 1.]


In [127]:
# pratice :

import numpy as np

A = np.array([[2,3],
              [4,5]])

B = np.array([[6,7],
              [8,9]])

print("1️⃣ Dot product:",np.dot(A,B))

print("2️⃣ Matrix multiplication:",np.matmul(A,B))

print("3️⃣ Determinant of A:",np.linalg.det(A))

1️⃣ Dot product: [[36 41]
 [64 73]]
2️⃣ Matrix multiplication: [[36 41]
 [64 73]]
3️⃣ Determinant of A: -2.0


# 20️⃣ Random Module 

Random numbers help in:

- Creating sample datasets
- Splitting training/testing data
- Initializing model weights
- Running statistical experiments

1. Random numbers
2. Random distributions

# 1️⃣ Random Numbers

Random numbers are **numbers generated unpredictably by a computer program.**

NumPy provides many functions to generate them.

In [128]:
import numpy as np

# random numbers between 0 and 1
arr = np.random.rand(5)

print(arr)

[0.62296636 0.05847376 0.03286787 0.77100311 0.35255797]


In [129]:
np.random.rand(5)

array([0.62742143, 0.59583043, 0.26489351, 0.79948997, 0.30403604])

In [130]:
# Random Integers
np.random.randint(1,10,5)

array([5, 3, 9, 4, 8])

In [131]:
# Random Choice
arr = [10,20,30,40]

np.random.choice(arr,2)

array([40, 40])

# 2️⃣ Random Distributions

In statistics, data often follows **certain distributions.**

##### Examples:

- Normal distribution
- Uniform distribution
- Binomial distribution

These are widely used in **data science experiments.**

# 🔹 Normal Distribution

Normal distribution is also called **Gaussian distribution.**

It looks like a **bell curve.**

- Mean = **center value**
- Standard deviation = **spread**

In [133]:
np.random.randn(5) # Values can be positive or negative.

array([-1.65235792, -1.01914035,  0.30280917, -0.64829935, -0.18629517])

## 🔹 Uniform Distribution

All numbers have **equal probability.**

In [134]:
np.random.uniform(1,10,5)

array([1.67670476, 1.35966372, 8.45263879, 9.12719455, 5.20584157])

# 🧠 Reproducible Results (Very Important)

In data science experiments, we want **same results every time.**

###### Use:
```
np.random.seed(42)

In [136]:
np.random.seed(42)  #Every run → same numbers.
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


In [145]:
# pratice :

import numpy as np

arr = np.random.rand(5)
arr2 =np.random.randint(1,20,5)
arr3 =np.random.randn(5)
arr4 = np.random.choice(5)
arr5 =np.random.uniform(1,22,5)

print("1️⃣ 5 random numbers between 0 and 1:",arr)
print("2️⃣ 5 random integers between 10 and 20:",arr2)
print("3️⃣ 5 numbers from normal distribution:",arr3)
print("4 choice:",arr4)
print("5 UNIFORM :",arr5)

1️⃣ 5 random numbers between 0 and 1: [6.47690121e-01 5.20376995e-04 3.52568856e-01 3.04781258e-01
 1.64655853e-01]
2️⃣ 5 random integers between 10 and 20: [ 9  5  1 19 10]
3️⃣ 5 numbers from normal distribution: [ 0.45293633 -0.16606091  0.21493883 -2.02231493 -0.94305681]
4 choice: 0
5 UNIFORM : [ 6.33222369  6.18439732 15.62238973 15.95768239  4.10982553]


# 📘 PHASE 5 — Performance & Optimization
### 21️⃣ Vectorization :
Vectorization means **performing operations on entire arrays at once instead of using loops.**

Instead of processing **one element at a time**, NumPy processes **all elements together.**

# 3️⃣ Code Example
### ❌ Without Vectorization (Using Loop)

In [146]:
import numpy as np

arr = np.array([1,2,3,4,5])

result = []

for i in arr:
    result.append(i * 2)

print(result)

[2, 4, 6, 8, 10]


# ✅ With Vectorization

In [147]:
import numpy as np

arr = np.array([1,2,3,4,5])

result = arr * 2

print(result)

[ 2  4  6  8 10]


# 4️⃣ Code Explanation
## Loop Version
Python processes **element by element
Slow for large datasets**

## Vectorized Version
NumPy processes the **whole array in one operation
Very fast**

This happens because NumPy is implemented in C internally, which is faster than Python loops.

# Performance Example

In [148]:
import numpy as np
import time

arr = np.arange(1000000)

# Loop method
start = time.time()

result = []
for i in arr:
    result.append(i * 2)

end = time.time()
print("Loop time:", end-start)

Loop time: 0.40990138053894043


## Vectorized version:

In [150]:
start = time.time()

result = arr * 2

end = time.time()
print("Vectorized time:", end-start) # Vectorized code is much faster

Vectorized time: 0.002991199493408203


In [154]:
# pratice 
import numpy as np

arr = np.array([10,20,30,40,50])

print("1️⃣ Add 5 to every element:",arr+5)
print("2️⃣ Multiply every element by 3:",arr*5)
print("3️⃣ Square every element:",arr**2)

1️⃣ Add 5 to every element: [15 25 35 45 55]
2️⃣ Multiply every element by 3: [ 50 100 150 200 250]
3️⃣ Square every element: [ 100  400  900 1600 2500]


# 22️⃣ Why NumPy is Faster than Python


NumPy is faster than Python because:

- 1️⃣ Vectorization
- 2️⃣ Written in C language
- 3️⃣ Uses contiguous memory
- 4️⃣ Avoids Python loops

These features make NumPy much faster for numerical calculations.

In [155]:
# Python List (Slow)

import time

arr = list(range(1000000))

start = time.time()

result = []
for i in arr:
    result.append(i * 2)

end = time.time()

print("Python loop time:", end-start)

Python loop time: 0.26130199432373047


In [156]:
# NumPy Version (Fast)

import numpy as np
import time

arr = np.arange(1000000)

start = time.time()

result = arr * 2

end = time.time()

print("NumPy time:", end-start)

NumPy time: 0.019946813583374023


# 23️⃣ Memory Efficiency

Memory efficiency means using **less computer memory while storing and processing data.**

NumPy arrays are** more memory-efficient than Python lists because:**

- All elements have the same data type
- Data is stored in contiguous memory blocks

* Python list → more memory
* 
NumPy array → less memory

In [159]:
# Python List Memory
import sys

arr = [1,2,3,4,5]

print(sys.getsizeof(arr))

#Stores pointers to objects
#Consumes more memory

104


In [160]:
# NumPy Array Memory
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr.nbytes)

# Stores raw values directly
# Consumes less memory

20


# 24️⃣ Avoiding Loops

In NumPy, we should **avoid Python loops and use vectorized operations.**

Loops are slower because **Python processes one element at a time.**

**Vectorization processes entire arrays at once.**

# 📘 PHASE 6 — Real Data Science Usage
## 25️⃣ NumPy with Pandas


Pandas uses NumPy internally for **fast numerical operations.**

#### That means:
```
Pandas DataFrame
        ↓
   NumPy Arrays
```

Most numerical calculations in Pandas are actually done using NumPy arrays.

## 3️⃣ Code Example:

In [161]:
# Import Libraries
import numpy as np
import pandas as pd

# Create NumPy Array
arr = np.array([10,20,30,40,50])

# Convert NumPy Array → Pandas Series
series = pd.Series(arr)

print(series)


0    10
1    20
2    30
3    40
4    50
dtype: int32


# Example 2 — NumPy Array → DataFrame

In [162]:
import numpy as np
import pandas as pd

data = np.array([
    [25,50000],
    [30,60000],
    [35,70000]
])

df = pd.DataFrame(data, columns=["Age","Salary"])

print(df)

   Age  Salary
0   25   50000
1   30   60000
2   35   70000


## 🧠 Access NumPy Data from Pandas

Pandas data can be **converted back to NumPy.**
```

df.values

or

df.to_numpy()

In [163]:
arr = df.to_numpy()

print(arr)

[[   25 50000]
 [   30 60000]
 [   35 70000]]


In [165]:
import numpy as np
import pandas as pd

arr = np.array([
    [101,500],
    [102,600],
    [103,700]
])

df = pd.DataFrame(arr,columns=["ProductID","Sales"])
print(df)

   ProductID  Sales
0        101    500
1        102    600
2        103    700


# 26️⃣ NumPy in Machine Learning

Machine Learning models mostly work with **vectors and matrices.**

NumPy helps to perform operations such as:

- Matrix multiplication
- Feature scaling
- Predictions
- Gradient calculations

These operations are extremely **fast using NumPy.**

In [168]:
import numpy as np

# Features: [size, rooms]
X = np.array([
    [1000,2],
    [1500,3],
    [2000,4]
])

# Model weights
weights = np.array([0.3, 50])

# Prediction
predictions = X @ weights

#This performs matrix multiplication.
#Each row is multiplied with weights to produce a prediction value.

print(predictions)

[400. 600. 800.]


# 27️⃣ Data Preprocessing with NumPy

Data preprocessing means **preparing raw data** so that it can be used by **machine learning models.**

### Common preprocessing tasks:

- Handling missing values
- Feature scaling
- Normalization
- Filtering invalid data

NumPy helps perform these operations **quickly and efficiently.**

# 3️⃣ Code Example
## Handling Missing Values

In [169]:
import numpy as np

data = np.array([80, 90, np.nan, 75, 100])

# replace missing values with mean
mean_value = np.nanmean(data)

data[np.isnan(data)] = mean_value

print(data)

[ 80.    90.    86.25  75.   100.  ]


# Feature Scaling (Very Important)

Machine learning models work better when **features are on similar scales**.

#### Example dataset:
```
Age = 20,30,40
Salary = 20000,80000,150000
```
Salary values are much larger.

We scale them using normalization.

In [170]:
# Normalization
import numpy as np

data = np.array([10,20,30,40,50])
 
normalized = (data - np.min(data)) / (np.max(data) - np.min(data)) # formula of normalization

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


# 28️⃣ Feature Scaling using NumPy


Feature scaling means adjusting values of different features so that they are in a similar range.

#### Example dataset:
```
Age        → 20, 30, 40
Salary     → 20000, 80000, 150000
```
##### Problem:

- Salary values are much larger than Age values

- This can confuse machine learning models.

- Feature scaling fixes this issue.

In [172]:
# 3️⃣ Code Example — Min-Max Scaling

import numpy as np


data = np.array([10,20,30,40,50])

scaled = (data - np.min(data)) / (np.max(data) - np.min(data))

print(scaled)

[0.   0.25 0.5  0.75 1.  ]


In [173]:
# Example with Dataset
import numpy as np

data = np.array([
    [25,50000],
    [30,60000],
    [35,80000],
    [40,100000]
])

scaled = (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))

print(scaled)

[[0.         0.        ]
 [0.33333333 0.2       ]
 [0.66666667 0.6       ]
 [1.         1.        ]]


# Another Important Scaling — Standardization

Standardization converts data to mean = 0 and standard deviation = 1.

In [174]:
import numpy as np

data = np.array([10,20,30,40,50])

standardized = (data - np.mean(data)) / np.std(data)

print(standardized)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
