NUMPY WITH ARRYS


In [1]:
# importing the numpy
import numpy as np
a=np.array(10) # 0 Dimensional Array
b=np.array([1,2,3,4]) # 1 Dimensional Array
c=np.array([[5,6,7],[8,9,10]]) # 2 Dimensional Array
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9] ,[10,11,12]]]) # 3 Dimensional Array


print(f'Array With Zero(0) Dimensional : {a}\n')
print(f'Array With One(1) Dimensional : {b}\n')
print(f'Array With Two(2) Dimensional : {c}\n')
print(f'Array with Three(3) Dimensional : {d}\n')

Accessing From ARRAY

In [3]:
B=b[1]
print(f'From 1D :{B}')

C= c[1][1]
print(f'From 2D :{C}')

D =d[1][1][2]
print(f'From 3D :{D}')

From 1D :2
From 2D :9
From 3D :12


asarray() With nditer

In [16]:
z=np.asarray(c,dtype=float,order="f")
print(z)

[[ 5.  6.  7.]
 [ 8.  9. 10.]]


In [19]:
for i in np.nditer(c):
    print(i)

5
6
7
8
9
10


In [29]:
x=y"Welcome"
y=np.frombuffer(a,dtype="S1",count=7 offset=0)
print(Y)

SyntaxError: invalid syntax (1780441077.py, line 1)

In [30]:
a=b"Hi welcome to numpy"
b=np.frombuffer(a,dtype="S1",count=7,offset=0)
print(b)

[b'H' b'i' b' ' b'w' b'e' b'l' b'c']


In [32]:
np.fromiter(a,dtype="S1",count=4)

array([b'7', b'1', b'3', b'1'], dtype='|S1')

Initializing The Array :


In [35]:
#1.Zeros()

b=np.zeros([2,3])
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
#2.Full()

c=np.full([2,3],7)
c

array([[7, 7, 7],
       [7, 7, 7]])

In [41]:
#3.ones()

h=np.ones([2,3])
h

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
#4.eye() used to diagonal elements ate(1) remaining All(0)
n=np.eye(5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

NUMERICAL RANGE  :


In [48]:
a=np.arange(1,100,10)
a

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [54]:
a.reshape(5,2) # 5*2=10  [10 elements in Array

array([[ 1, 11],
       [21, 31],
       [41, 51],
       [61, 71],
       [81, 91]])

In [58]:
# 2 linspace() 
z=np.linspace(0,100,10, endpoint=False,retstep=True)
z

(array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]), 10.0)

In [60]:
# 3.logspace()
n=np.logspace(0,100,10,base=2)
n

array([1.00000000e+00, 2.21196235e+03, 4.89277742e+06, 1.08226394e+10,
       2.39392709e+13, 5.29527657e+16, 1.17129524e+20, 2.59086096e+23,
       5.73088689e+26, 1.26765060e+30])

ARRAY PROPERTIES :



In [62]:
# 1.Size of ARRAY
np.size(b)

6

In [67]:
# 2.shape of Array
np.shape(c)

(2, 3)

OPERATIONS WITH ARRAY : 

In [69]:
# 1.SLICING
a=np.arange(0,100,10)
a[1:5]


array([10, 20, 30, 40])

In [70]:
# 2.copy()
b=np.copy(a)
b

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [72]:
#3.view()
c=a.view()
c

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [80]:
# 4.Sort()
np.sort(d,axis=1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
# 5.append()
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.append(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
# 6. Insert 
np.insert(a,3,45)

array([ 1,  2,  3, 45,  4])

In [86]:
# 7.Concatenate
np.concatenate((a,b)) # same as Append

array([1, 2, 3, 4, 5, 6, 7, 8])

In [96]:
#8.Stack
c=np.stack((a,b))
f=np.vstack((a,b))
g=np.hstack((a,b))
h=np.dstack((a,b))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [97]:
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [98]:
print(f)

[[1 2 3 4]
 [5 6 7 8]]


In [99]:
print(g)

[1 2 3 4 5 6 7 8]


In [100]:
print(h)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [101]:
#9.split()
np.split(a,2)

[array([1, 2]), array([3, 4])]

In [104]:
#10.WHERE
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [110]:
np.where(a ==3)

(array([1], dtype=int64), array([0], dtype=int64))

In [122]:
#SEARCH SORTED : IT SHOWS INDEX
k=np.array([10,20,3,44,5,55,66,77,777,779])
np.searchsorted(k,777)

8

In [116]:
np.searchsorted(k,[55,66,77])

array([5, 6, 7], dtype=int64)

ARITHMETIC OPERATIONS : 


In [7]:
import numpy as np
a=np.arange(1,100,10)

b=np.arange(2,100,10)
print(a,b)

[ 1 11 21 31 41 51 61 71 81 91] [ 2 12 22 32 42 52 62 72 82 92]


In [19]:
# 1.Addition
z=np.add(a,b)

# 2.Subtract
y=np.subtract(a,b)

# 3.multiplication
x=np.multiply(a,b)

# 4.Division
w=np.divide(a,b)

# 5.Exponant
#v =np.exp(a,b)

#6.Square root
#u =np.sqrt(a,b)

# 7.Equal
t=np.array_equal(a,b)



In [20]:
print(f'Addition of a,b :{z}')
print(f'Subtraction of a,b :{y}')
print(f'multiplication of a,b :{x}')
print(f'Division of a,b :{w}')
#print(f'EXP of a,b :{v}')
#print(f'Square root  of a,b :{u}')
print(f'Equal of a,b :{t}')


Addition of a,b :[  3  23  43  63  83 103 123 143 163 183]
Subtraction of a,b :[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
multiplication of a,b :[   2  132  462  992 1722 2652 3782 5112 6642 8372]
Division of a,b :[0.5        0.91666667 0.95454545 0.96875    0.97619048 0.98076923
 0.98387097 0.98611111 0.98780488 0.98913043]
Equal of a,b :False


ARRAY FUNCTIONS:

In [23]:
a=np.arange(10,100,10)

# 1.minimum 
q=np.min(a)

# 2.Maximum
w=np.max(a)

# 3.Sum
e=np.sum(a)

# 4.Mean
r=np.mean(a)

# 5.Median
t=np.median(a)

# 6.Variance

y=np.var(a)

# 7.Standard Diviation

u=np.std(a)


In [25]:
print(f'The Array Elements are :{a}')
print(f'Minimum Number is :{q}')
print(f'Maximum Number is :{w}')
print(f'Sum Number is :{e}')
print(f'Mean Number is :{r}')
print(f'Median Number is :{t}')
print(f'Variance Number is :{y}')
print(f'Std Number is :{u}')

The Array Elements are :[10 20 30 40 50 60 70 80 90]
Minimum Number is :10
Maximum Number is :90
Sum Number is :450
Mean Number is :50.0
Median Number is :50.0
Variance Number is :666.6666666666666
Std Number is :25.81988897471611
